Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.network "private_network", type: "dhcp"

  config.vm.provision "file", source: "./empty_file.txt", destination: "/home/vagrant/empty_file.txt"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y python3 python3-pip libpq-dev
    pip3 install psycopg2-binary Django
  SHELL
end
